/* Edit portfolio content here. Project cards are intentionally placeholders. */
window.PORTFOLIO = {
  profile: {
    name: "Jareyatham Masong",
    thaiName: "จริยธรรม มาสงค์",
    avatar: "assets/jareyatham-profile.gif",
    resume: "assets/Jareyatham-Masong-Resume.pdf",
  },
  nav: [
    ["home", "index.html", "หน้าหลัก", "Home"],
    ["about", "about.html", "เกี่ยวกับ", "About"],
    ["projects", "projects.html", "ผลงาน", "Projects"],
    ["experience", "experience.html", "ประสบการณ์", "Experience"],
    ["tools", "tools.html", "เครื่องมือ", "Tools"],
    ["contact", "contact.html", "ติดต่อ", "Contact"],
    ["resume", "resume.html", "เรซูเม่", "Resume"],
  ],
  contact: [
    [
      "GitHub",
      "github.com/Jareyatham-mas",
      "https://github.com/Jareyatham-mas",
      "ดูโค้ดและโปรเจกต์ของผม",
      "View my code and projects",
    ],
    [
      "LinkedIn",
      "jareyatham-masong",
      "https://www.linkedin.com/in/jareyatham-masong-9aa032436",
      "เชื่อมต่อผ่าน LinkedIn",
      "Connect on LinkedIn",
    ],
    [
      "Instagram",
      "@nothmoto",
      "https://www.instagram.com/nothmoto/",
      "ชีวิตและกิจกรรมของผม",
      "Life and activities",
    ],
    [
      "Facebook",
      "Jareyatham Masong",
      "https://www.facebook.com/share/1EX7DmgQxS/?mibextid=wwXIfr",
      "ติดตามผ่าน Facebook",
      "Follow on Facebook",
    ],
    [
      "LINE",
      "เพิ่มเพื่อนผ่าน LINE",
      "https://line.me/ti/p/Jwrizo2JEk",
      "เปิด LINE เพื่อพูดคุย",
      "Open LINE to chat",
    ],
    [
      "Email",
      "jareyatham.work@gmail.com",
      "mailto:jareyatham.work@gmail.com",
      "ส่งอีเมลถึงผม",
      "Send me an email",
    ],
  ],
  projects: [
    [
      "01",
      "Project title",
      "Project title",
      "เพิ่มชื่อผลงานและคำอธิบายสั้น ๆ ของคุณที่นี่",
      "Add your project name and a concise description here.",
      "บทบาทของคุณ",
      "Your role",
      "React · API · Database",
    ],
    [
      "02",
      "Project title",
      "Project title",
      "เพิ่มผลงานอีกชิ้น พร้อมปัญหาที่โปรเจกต์นี้แก้ไข",
      "Add another project and the problem it solves.",
      "บทบาทของคุณ",
      "Your role",
      "Web · UX · Testing",
    ],
    [
      "03",
      "Project title",
      "Project title",
      "เพิ่ม case study หรือโปรเจกต์จากการเรียนรู้",
      "Add a case study or a learning project.",
      "บทบาทของคุณ",
      "Your role",
      "Automation · n8n",
    ],
    [
      "04",
      "Project title",
      "Project title",
      "เพิ่มผลงานที่คุณต้องการนำเสนอในอนาคต",
      "Add work you would like to showcase later.",
      "บทบาทของคุณ",
      "Your role",
      "Design · Development",
    ],
  ],
  tools: [
    [
      "การพัฒนาเว็บ",
      "Web development",
      [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Node.js",
        "Express.js",
        "ASP.NET MVC",
      ],
    ],
    [
      "ภาษาและฐานข้อมูล",
      "Languages & databases",
      ["Python", "C#", "SQL", "MySQL", "SQL Server", "MongoDB"],
    ],
    [
      "การทดสอบและ API",
      "Testing & API",
      ["Postman", "Swagger", "REST API", "Test Case Design", "Bug Reporting"],
    ],
    [
      "เวิร์กโฟลว์และการทำงานร่วมกัน",
      "Workflow & collaboration",
      ["n8n", "Git", "GitHub", "Docker", "Trello"],
    ],
  ],
};
